services:
  tirexshop.api:
    image: ${DOCKER_REGISTRY-}tirexshopapigateway
    container_name: ApiGateway
    ports: 
     - "5000:8080"
    expose:
      - "9464"
    build:
      context: .
      dockerfile: src/WebApps/TirexShopApiGateway/TirexShop.API/Dockerfile
    networks:
     - tirexshop-network
    depends_on:
      - alloy
  
  profileservice.api:
    image: profileservice.api
    container_name: ProfileService
    ports:
      - "5002:8080"
    expose:
      - "9464"
    build:
      context: .
      dockerfile: src/Services/ProfileService/ProfileService.API/Dockerfile
    networks:
      - tirexshop-network
    depends_on:
      - alloy
      
      
  prometheus:
    image: prom/prometheus:v3.6.0
    container_name: prometheus
    ports:
      - "9090:9090"
    volumes:
      - prometheus-data:/prometheus
    command:
      --web.enable-remote-write-receiver
      --config.file=/etc/prometheus/prometheus.yml
    networks:
      - tirexshop-network
  
  tempo:
    image: grafana/tempo
    container_name: tempo
    ports:
      - "4327:4317"
      - "3200:3200"
    volumes:
      - tempo-data:/var/tempo
      - ./Infrastructure/Monitoring/tempo/tempo.yaml:/etc/tempo.yaml
    command: ["-config.file=/etc/tempo.yaml"]
    networks:
      - tirexshop-network
      
      
  alloy:
    image: grafana/alloy:v1.10.2
    container_name: alloy
    ports:
      - 12345:12345
      - 4317:4317
      - 4318:4318
    volumes:
      - ./Infrastructure/Monitoring/alloy/config.alloy:/etc/alloy/config.alloy
      - /var/run/docker.sock:/var/run/docker.sock
      - /:/rootfs:ro
      - /var/run:/var/run:ro
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro
      - /dev/disk/:/dev/disk:ro
    command:
      run --server.http.listen-addr=0.0.0.0:12345 --storage.path=/var/lib/alloy/data /etc/alloy/config.alloy
    networks:
      - tirexshop-network
  
  
  loki:
    image: grafana/loki:latest
    container_name: loki
    ports:
      - "4001:3100"
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
    volumes:
      - ./Infrastructure/Monitoring/loki-config.yaml:/etc/loki/local-config.yaml
      - loki-data:/loki
    command:
      -config.file=/etc/loki/local-config.yaml
    networks:
      - tirexshop-network
  
  grafana:
    image: grafana/grafana:12.3.0-17900959199
    container_name: grafana
    ports:
      - "4002:3000"
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
    volumes:
      - ./Infrastructure/Monitoring/grafana/datasources.yaml:/etc/grafana/provisioning/datasources/datasources.yaml
      - ./Infrastructure/Monitoring/grafana/dashboards.yaml:/etc/grafana/provisioning/dashboards/dashboards.yaml
      - ./Infrastructure/Monitoring/grafana/dashboards:/var/lib/grafana/dashboards
      - grafana-data:/var/lib/grafana
    networks:
      - tirexshop-network

  cadvisor:
    image: gcr.io/cadvisor/cadvisor:latest
    container_name: cadvisor
    ports:
      - "8081:8080"
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:rw
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro
    networks:
      - tirexshop-network

  keycloak:
    image: quay.io/keycloak/keycloak:26.3.4
    container_name: keycloak
    command:
      - start-dev
      - --import-realm
    ports:
      - "18080:8080"
    environment:
      # Админ
      - KEYCLOAK_ADMIN=admin
      - KEYCLOAK_ADMIN_PASSWORD=admin
      - KC_HEALTH_ENABLED=true
      # Настройки SPI Kafka (runtime)
      - KC_SPI_EVENTS_LISTENER_KAFKA_EVENT_LISTENER_ENABLED=true
      - KC_SPI_EVENTS_LISTENER_KAFKA_EVENT_LISTENER_BOOTSTRAP_SERVERS=kafka:9092
      - KC_SPI_EVENTS_LISTENER_KAFKA_EVENT_LISTENER_TOPIC=user-events
      - KC_SPI_EVENTS_LISTENER_KAFKA_EVENT_LISTENER_REALM=TirexShop
    volumes:
      # Данные Keycloak
      - keycloak-data:/opt/keycloak/data
      # Твой JAR SPI
      - ./Infrastructure/Keycloak/providers:/opt/keycloak/providers:ro
      # Импорт реальмов
      - ./Infrastructure/Keycloak/realms:/opt/keycloak/data/import:ro
    networks:
      - tirexshop-network
  
  
  zookeeper:
    image: confluentinc/cp-zookeeper:7.6.0
    container_name: zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
    ports:
      - "2181:2181"
    networks:
      - tirexshop-network

  kafka:
    image: confluentinc/cp-kafka:7.6.0
    container_name: kafka
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092  # для работы внутри Docker
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    networks:
      - tirexshop-network

  kafka-ui:
    image: provectuslabs/kafka-ui
    container_name: kafka-ui
    ports:
      - "9080:8080"
    depends_on:
      - kafka
    environment:
      - KAFKA_CLUSTERS_0_NAME=local
      - KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS=kafka:9092
    networks:
      - tirexshop-network
  
  pgadmin:
    image: dpage/pgadmin4:9.8.0
    container_name: pgadmin
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: root
    ports:
      - "5050:80"
    volumes:
      - pgadmin-data:/var/lib/pgadmin
    networks:
      - tirexshop-network
      
  profile_db:
    image: postgres:latest
    container_name: profile_db
    ports:
      - "5434:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 22848
      POSTGRES_DB: profile_db
    volumes:
      - profile_db-data:/var/lib/postgresql/data
    networks:
      - tirexshop-network

volumes:
 profile_db-data:
 loki-data:
 grafana-data:
 prometheus-data:
 tempo-data:
 keycloak-data:
 pgadmin-data:
 
networks:
  tirexshop-network:
    driver: bridge
    external: true