services:
  tirexshop.api:
    image: ${DOCKER_REGISTRY-}tirexshopapigateway
    container_name: ApiGateway
    ports: 
     - "5000:8080"
    build:
      context: .
      dockerfile: src/WebApps/TirexShopApiGateway/TirexShop.API/Dockerfile
    networks:
     - tirexshop-network
 
  identityservice.api:
    image: ${DOCKER_REGISTRY-}identityserviceapi
    container_name: IdentityService
    ports: 
     - "5001:8080"
    build:
      context: .
      dockerfile: src/Services/IdentityService/IdentityService.API/Dockerfile
    networks:
     - tirexshop-network

  

  identity_db:
   image: postgres:latest
   container_name: identity_db
   ports: 
    - "5434:5432"
   environment:
    POSTGRES_USER: postgres
    POSTGRES_PASSWORD: 22848
    POSTGRES_DB: identity_db
   volumes: 
    - postgres-data:/var/lib/postgresql/data
   networks:
    - tirexshop-network

volumes:
 postgres-data:
 
networks:
  tirexshop-network:
    driver: bridge
    external: true

