services:
  tirexshop.api:
    image: ${DOCKER_REGISTRY-}tirexshopapigateway
    container_name: ApiGateway
    ports: 
     - "5000:8080"
    build:
      context: .
      dockerfile: src/WebApps/TirexShopApiGateway/TirexShop.API/Dockerfile
    networks:
     - tirexshop-network
 
  identityservice.api:
    image: ${DOCKER_REGISTRY-}identityserviceapi
    container_name: IdentityService
    ports: 
     - "5001:8080"
    build:
      context: .
      dockerfile: src/Services/IdentityService/IdentityService.API/Dockerfile
    networks:
     - tirexshop-network
  
  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./Infrastructure/Monitoring/prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheus-data:/prometheus
    networks:
      - tirexshop-network
  
  promtail:
    image: grafana/promtail:latest
    container_name: promtail
    ports:
      - "4000:4000"
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
    volumes:
      - /var/lib/docker/containers:/var/lib/docker/containers:ro
      - /var/lib/docker.sock:/var/run/docker.sock
      - ./Infrastructure/Monitoring/promtail-config.yaml:/etc/promtail/config.yml
    command:
      - -config.file=/etc/promtail/config.yml
    networks:
      - tirexshop-network
  
  loki:
    image: grafana/loki:latest
    container_name: loki
    ports:
      - "4001:3100"
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
    volumes:
      - ./Infrastructure/Monitoring/loki-config.yaml:/etc/loki/local-config.yaml
    networks:
      - tirexshop-network
  
  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    ports:
      - "4002:3000"
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
    volumes:
      - ./Infrastructure/Monitoring/grafana/datasources.yaml:/etc/grafana/provisioning/datasources/datasources.yaml
      - ./Infrastructure/Monitoring/grafana/dashboards.yaml:/etc/grafana/provisioning/dashboards/dashboards.yaml
      - ./Infrastructure/Monitoring/grafana/dashboards:/var/lib/grafana/dashboards
      - grafana-data:/var/lib/grafana
    networks:
      - tirexshop-network
    
  
  cadvisor:
    image: gcr.io/cadvisor/cadvisor:latest
    container_name: cadvisor
    ports:
      - "8081:8080"
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:rw
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro
    networks:
      - tirexshop-network

  identity_db:
   image: postgres:latest
   container_name: identity_db
   ports: 
    - "5434:5432"
   environment:
    POSTGRES_USER: postgres
    POSTGRES_PASSWORD: 22848
    POSTGRES_DB: identity_db
   volumes: 
    - postgres-data:/var/lib/postgresql/data
   networks:
    - tirexshop-network

volumes:
 postgres-data:
 grafana-data:
 prometheus-data:
 
networks:
  tirexshop-network:
    driver: bridge
    external: true

