{
 "title": "ASP.NET OTEL Metrics from OTEL Collector",
 "description": "Shows .NET and ASP.NET metrics pushed to OTEL Collector and scraped by Prometheus from OTEL Collector",
 "tags": [
  "dotnet",
  "opentelemetry",
  "otel",
  "prometheus",
  "process",
  "runtime",
  "httpclient",
  "aspnetcore"
 ],
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   {
    "name": "job",
    "label": "Job",
    "query": {
     "query": "label_values(aspnetcore_routing_match_attempts_total,job)"
    }
   },
   {
    "name": "instance",
    "label": "Instance",
    "query": {
     "query": "label_values(aspnetcore_routing_match_attempts_total{job=~\"$job\"}, instance)"
    }
   },
   {
    "name": "http_client_peer_name",
    "label": "HTTP Client Pear Name",
    "query": {
     "query": "label_values(http_client_request_duration_seconds_bucket{exported_job=\"$job\", exported_instance=\"$instance\"},server_address)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Process", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "CPU Usage",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 11, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "irate(process_cpu_time_seconds_total{job=~\"$job\", instance=~\"$instance\"}[$__rate_interval])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 10, "x": 11, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "max_over_time(process_memory_usage_bytes{job=~\"$job\", instance=~\"$instance\"}[$__rate_interval])",
     "legendFormat": "Memory Usage"
    }
   ]
  },
  {
   "title": "Threads",
   "type": "stat",
   "gridPos": { "h": 9, "w": 3, "x": 21, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max_over_time(process_threads{job=~\"$job\", instance=~\"$instance\"}[$__rate_interval])",
     "legendFormat": "Threads"
    }
   ]
  },
  { "title": "Runtime", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 10 } },
  {
   "title": "General Memory Usage",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "max_over_time(process_runtime_dotnet_gc_committed_memory_size_bytes{job=~\"$job\", instance=~\"$instance\"}[$__rate_interval])",
     "legendFormat": "Committed Memory Size"
    },
    {
     "expr": "max_over_time(process_runtime_dotnet_gc_objects_size_bytes{job=~\"$job\", instance=~\"$instance\"}[$__rate_interval])",
     "legendFormat": "Objects Size"
    },
    {
     "expr": "irate(process_runtime_dotnet_gc_allocations_size_bytes_total{job=~\"$job\", instance=~\"$instance\"}[$__rate_interval])",
     "legendFormat": "Allocations Size"
    }
   ]
  },
  {
   "title": "Heap Generations (bytes)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "max_over_time(process_runtime_dotnet_gc_heap_size_bytes{job=~\"$job\", instance=~\"$instance\"}[$__rate_interval])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Heap Fragmentation (bytes)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "max_over_time(process_runtime_dotnet_gc_heap_fragmentation_size_bytes{job=~\"$job\", instance=~\"$instance\"}[$__rate_interval])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "GC Collections",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "rate(process_runtime_dotnet_gc_collections_count_total{job=~\"$job\", instance=~\"$instance\"}[$__rate_interval])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Exceptions",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "increase(process_runtime_dotnet_exceptions_count_total{job=~\"$job\", instance=~\"$instance\"}[$__rate_interval])",
     "legendFormat": "Exceptions"
    }
   ]
  },
  {
   "title": "ThreadPool Threads",
   "type": "stat",
   "gridPos": { "h": 9, "w": 4, "x": 16, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max_over_time(process_runtime_dotnet_thread_pool_threads_count{job=~\"$job\", instance=~\"$instance\"}[$__rate_interval])",
     "legendFormat": "ThreadPool Threads"
    }
   ]
  },
  {
   "title": "ThreadPool Threads Queue Length",
   "type": "stat",
   "gridPos": { "h": 9, "w": 4, "x": 20, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max_over_time(process_runtime_dotnet_thread_pool_queue_length{job=~\"$job\", instance=~\"$instance\"}[$__rate_interval])",
     "legendFormat": "ThreadPool Threads Queue Length"
    }
   ]
  },
  { "title": "HTTP Server", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 29 } },
  {
   "title": "Responses Duration",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 30 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.50, sum(rate(http_server_request_duration_seconds_bucket{job=~\"$job\", instance=~\"$instance\"}[$__rate_interval])) by (le))",
     "legendFormat": "p50"
    },
    {
     "expr": "histogram_quantile(0.75, sum(rate(http_server_request_duration_seconds_bucket{job=~\"$job\", instance=~\"$instance\"}[$__rate_interval])) by (le))",
     "legendFormat": "p75"
    },
    {
     "expr": "histogram_quantile(0.90, sum(rate(http_server_request_duration_seconds_bucket{job=~\"$job\", instance=~\"$instance\"}[$__rate_interval])) by (le))",
     "legendFormat": "p90"
    },
    {
     "expr": "histogram_quantile(0.95, sum(rate(http_server_request_duration_seconds_bucket{job=~\"$job\", instance=~\"$instance\"}[$__rate_interval])) by (le))",
     "legendFormat": "p95"
    },
    {
     "expr": "histogram_quantile(0.98, sum(rate(http_server_request_duration_seconds_bucket{job=~\"$job\", instance=~\"$instance\"}[$__rate_interval])) by (le))",
     "legendFormat": "p98"
    },
    {
     "expr": "histogram_quantile(0.99, sum(rate(http_server_request_duration_seconds_bucket{job=~\"$job\", instance=~\"$instance\"}[$__rate_interval])) by (le))",
     "legendFormat": "p99"
    },
    {
     "expr": "histogram_quantile(0.999, sum(rate(http_server_duration_milliseconds_bucket{job=~\"$job\", instance=~\"$instance\"}[$__rate_interval])) by (le))",
     "legendFormat": "p99.9"
    }
   ]
  },
  {
   "title": "Errors Rate",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 30 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum(rate(http_server_request_duration_seconds_count{exported_job=\"$job\", exported_instance=\"$instance\", http_response_status_code!~\"2..\"}[$__rate_interval]) or vector(0)) / sum(rate(http_server_request_duration_seconds_count{exported_job=\"$job\", exported_instance=\"$instance\"}[$__rate_interval]))",
     "legendFormat": "All"
    },
    {
     "expr": "sum(rate(http_server_request_duration_seconds_count{exported_job=\"$job\", exported_instance=\"$instance\", http_response_status_code=~\"4..\"}[$__rate_interval]) or vector(0)) / sum(rate(http_server_request_duration_seconds_count{exported_job=\"$job\", exported_instance=\"$instance\"}[$__rate_interval]))",
     "legendFormat": "4XX"
    },
    {
     "expr": "sum(rate(http_server_request_duration_seconds_count{exported_job=\"$job\", exported_instance=\"$instance\", http_response_status_code=~\"5..\"}[$__rate_interval]) or vector(0)) / sum(rate(http_server_request_duration_seconds_count{exported_job=\"$job\", exported_instance=\"$instance\"}[$__rate_interval]))",
     "legendFormat": "5XX"
    }
   ]
  },
  {
   "title": "HTTP Client ($http_client_peer_name)",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 39 },
   "repeat": "http_client_peer_name"
  },
  {
   "title": "Requests Duration",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 40 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.50, sum(rate(http_client_request_duration_seconds_bucket{job=~\"$job\", instance=~\"$instance\", server_address=\"$http_client_peer_name\"}[$__rate_interval])) by (le))",
     "legendFormat": "p50"
    },
    {
     "expr": "histogram_quantile(0.75, sum(rate(http_client_request_duration_seconds_bucket{job=~\"$job\", instance=~\"$instance\", server_address=\"$http_client_peer_name\"}[$__rate_interval])) by (le))",
     "legendFormat": "p75"
    },
    {
     "expr": "histogram_quantile(0.90, sum(rate(http_client_request_duration_seconds_bucket{job=~\"$job\", instance=~\"$instance\", server_address=\"$http_client_peer_name\"}[$__rate_interval])) by (le))",
     "legendFormat": "p90"
    },
    {
     "expr": "histogram_quantile(0.95, sum(rate(http_client_request_duration_seconds_bucket{job=~\"$job\", instance=~\"$instance\", server_address=\"$http_client_peer_name\"}[$__rate_interval])) by (le))",
     "legendFormat": "p95"
    },
    {
     "expr": "histogram_quantile(0.98, sum(rate(http_client_request_duration_seconds_bucket{job=~\"$job\", instance=~\"$instance\", server_address=\"$http_client_peer_name\"}[$__rate_interval])) by (le))",
     "legendFormat": "p98"
    },
    {
     "expr": "histogram_quantile(0.99, sum(rate(http_client_request_duration_seconds_bucket{job=~\"$job\", instance=~\"$instance\", server_address=\"$http_client_peer_name\"}[$__rate_interval])) by (le))",
     "legendFormat": "p99"
    },
    {
     "expr": "histogram_quantile(0.999, sum(rate(http_client_request_duration_seconds_bucket{job=~\"$job\", instance=~\"$instance\", server_address=\"$http_client_peer_name\"}[$__rate_interval])) by (le))",
     "legendFormat": "p99.9"
    }
   ]
  },
  {
   "title": "Errors Rate",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 40 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum(rate(http_client_request_duration_seconds_bucket{job=~\"$job\", instance=~\"$instance\", server_address=\"$http_client_peer_name\", http_response_status_code!~\"2..\"}[$__rate_interval]) or vector(0)) / sum(rate(http_client_request_duration_seconds_bucket{job=~\"$job\", instance=~\"$instance\", server_address=\"$http_client_peer_name\"}[$__rate_interval]))",
     "legendFormat": "All"
    },
    {
     "expr": "sum(rate(http_client_request_duration_seconds_bucket{job=~\"$job\", instance=~\"$instance\", server_address=\"$http_client_peer_name\", http_response_status_code=~\"4..\"}[$__rate_interval]) or vector(0)) / sum(rate(http_client_request_duration_seconds_bucket{job=~\"$job\", instance=~\"$instance\", server_address=\"$http_client_peer_name\"}[$__rate_interval]))",
     "legendFormat": "4XX"
    },
    {
     "expr": "sum(rate(http_client_request_duration_seconds_bucket{job=~\"$job\", instance=~\"$instance\", server_address=\"$http_client_peer_name\", http_response_status_code=~\"5..\"}[$__rate_interval]) or vector(0)) / sum(rate(http_client_request_duration_seconds_bucket{job=~\"$job\", instance=~\"$instance\", server_address=\"$http_client_peer_name\"}[$__rate_interval]))",
     "legendFormat": "5XX"
    }
   ]
  }
 ]
}