# keycloak.conf

# База данных (для разработки)
KC_DB=h2

# Порт для HTTP
KC_HTTP_PORT=8080

KC_HEALTH_ENABLED=true

# Конфигурация SPI для Kafka
# Мы создаём кастомный SPI 'kafka-event-listener'
spi.kafka-event-listener.enabled=true
spi.kafka-event-listener.bootstrap-servers=kafka:9092
spi.kafka-event-listener.topic=user-events
